# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test

      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "50"
          filename: "coverage.xml"

     # - name: Test Coverage Comparison of Added & Modified Files
  # You may pin to the exact commit or the version.
  # uses: AveryCameronUofR/test-coverage-check-gh-action@8bbd56b2c0f24baa564396dc96c9aecc334b5aa5
      #  uses: AveryCameronUofR/test-coverage-check-gh-action@1.1.1
       # with:
    # minimum coverage a new file has to have to pass
        #  minNewCoverage: 0.5 # optional, default is 0.8
    # Max amount coverage can reduce and pass
        # maxCoverageChange: 0.1 # optional, default is 0.1
    # Gitub Personal Access Token
         # token: "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"
    # Base ref branch to merge into and check cov against
         # branch: 'master'


  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: SonarCloud Scan
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=MariusUntaru_NoticeBoard-master
        env:
          SONAR_TOKEN: "d61d7effae2803f06c82a1d31511815d5ca0a57c"   
          
  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-latest
    needs: [test, sonar]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env: 
          "@MariusUntaru:registry": "https://npm.pkg.github.com"



  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [test, sonar]
    env:
      REPO: "mariusuntaru96/invoice-system"

    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u "mariusuntaru96" -p "bnK4tBU!frtXN2MHKAHzia"
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO

